name: f_web
description: An app built using Flutter for web

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.0.5

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter_web: any
  flutter_web_ui: any
  dio: 1.0.9

dev_dependencies:
  build_runner: ^1.4.0
  build_web_compilers: ^1.2.2
  pedantic: ^1.0.0

dependency_overrides:
  flutter_web:
    path: packages/flutter_web
  flutter_web_ui:
    path: packages/flutter_web_ui

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
